version: '3.8'

services:
  flask-api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

networks:
  default:
    name: "host"
    external: true