name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Define date variable
    - name: Set Date Variable
      id: set_date
      run: echo "DATE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ env.DATE_TAG }}

    - name: Set up Docker container for testing
      run: docker run -d --name test-container my-image-name:${{ env.DATE_TAG }}

    - name: Install dependencies inside Docker container
      run: docker exec test-container pip install -r /app/requirements.txt

    - name: Run pytest inside the Docker container
      run: docker exec test-container pytest test_api.py

    - name: Clean up the Docker container
      run: docker rm -f test-container

